title: Meu blog
author: Bruna Donadel
email: bruna.donadel@gmail.com
description: > # this means to ignore newlines until "exclude"
  Write an awesome description for your new site here. This could
  for example be used for SEO purposes.

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore

# Date format for posts
# refer to http://shopify.github.io/liquid/filters/date/ if you
# want to customize this
date_format: "%b %-d, %Y"

# generate social links in footer
social_links:
  twitter: bruna
  github:  bruna
  # facebook:
